export const siteConfig = {
  title: "XingHuiSama",
  faviconUrl: "/assets/pets/muqiu/avatar.png",
  authorName: "XingHuiSama",
  bio: "在代码、学术与分子动力学模拟间穿梭的普通人。",
  navTitle: "XingHuiSama",
  navSuffix: "の",
  navAfter: "楚子航",
  avatarUrl: "/assets/pets/muqiu/avatar.png",
  useGradient: false,
  themeColors: ["#0f766e", "#0f172a", "#c2410c", "#e2e8f0"],
  bgImages: ["/assets/site/background.png", "/assets/site/cover.png"],
  defaultPostCover: "/assets/site/cover.png",
  photoWallImage: "/assets/site/background.png",
  social: { github: "https://github.com/heiehiehi", gitee: "https://github.com/heiehiehi", google: "mailto:bilibiliwuwuwu@gmail.com", email: "3295587260@qq.com", qq: "3295587260", wechat: "XingHuisama" },
  counts: { photos: 128 },
  chatterTitle: "云端杂谈",
  chatterDescription: "代码、学术、提瓦特与泰拉大陆的碎片记录",
  danmakuList: ["在干嘛呢？", "前方高能反应！", "GROMACS 跑起来了吗？", "BUG 修复进度 99%", "今天背单词了吗？"],
  gitalkConfig: { clientID: "", clientSecret: "", repo: "", owner: "", admin: [""] },
  buildDate: "2026-03-23T00:00:00",
  footerBadges: [],
  icpConfig: { name: "萌ICP备 20260240号", link: "https://icp.gov.moe/?keyword=20260240" },
  petPageTitle: "AI 宠物",
  friendLinkApplyFormat: "名称：XingHuiSama\n简介：今天我也要学习吗\n链接：https://www.xinghuisama.top\n头像：/assets/pets/muqiu/avatar.png",
  enableLevelSystem: true,
};
